### ISSUE TITLE
Game settings screen

### ISSUE THREAD

**Issue by JasmineEllaine** [Keven-R/TicTac#11]
## Design:

- [x] Convert compact design to autolayout with specs
- [x] Compact specs
- [x] Medium specs
- [x] Expanded specs

## Dev:

- [x] Size and orientation handler
- [x] Compact UI
- [x] Medium UI
- [x] Expanded UI

### Subtasks:

- [x] Component - Radio
- [x] Component - PrimaryButton
- [x] Class - change handler to determine screen by height 

### Testing:

- [x] Mobile - portrait
- [x] Mobile - landscape
- [x] tablet - portrait
- [x] tablet - landscape
