### ISSUE TITLE
Profile screen

### ISSUE THREAD

**Issue by JasmineEllaine** [Keven-R/TicTac#13]
## Design:

- [x] Convert compact design to autolayout with specs
- [x] Default specs
- [x] Short screen height specs

## Dev:

- [x] Size and orientation handler
- [x] Default UI
- [x] Short screen UI

### Subtasks:

- [x] Assets - import all avatars any density
- [x] Type - labelSmall
- [x] Component - titleMedium
- [x] Component - bodyMedium
- [x] Component - BackButton
- [x] Component - SecondaryButton
- [x] Component - win ratio display (MarkerGraphics in Cards.kt)
- [x] Elements - Top nav
- [x] Elements - User data
- [x] Elements - Fixed buttons

- [x] UI Layout - match this one to the game settings screen
- [x] Elements - replace back button
- [x] Elements - replace content - avatar
- [x] Elements - replace content - stats
- [x] Elements - replace primary actions
- [x] Elements - add win ratio block for short
- [x] Elements - add win ratio block for default

## Testing:

- [x] Mobile - portrait
- [x] Mobile - landscape
- [x] tablet - portrait
- [x] tablet - landscape
