### ISSUE TITLE
Multiplayer settings screen

### ISSUE THREAD

**Issue by JasmineEllaine** [Keven-R/TicTac#18]
## Design:

- [x] Convert compact design to autolayout with specs
- [x] Compact specs
- [x] Medium specs
- [x] Expanded specs

## Dev:

- [x] Size and orientation handler
- [x] Compact UI
- [x] Medium UI
- [x] Expanded UI

### Subtasks:

- [x] Setup - new file
- [x] Setup - new destination
- [x] Components - PlayerSelectCard
- [x] Type - BodyLarge
- [x] Component - BodyLarge
- [x] Component - Avatar
- [x] Component - AvatarBlock

## Testing:

- [x] Mobile - portrait
- [x] Mobile - landscape
- [x] tablet - portrait
- [x] tablet - landscape
