### ISSUE TITLE
User Select Screen - entry from profile page

### ISSUE THREAD

**Issue by JasmineEllaine** [Keven-R/TicTac#20]
# Docs

- [Design specs + layout (Figma)](https://www.figma.com/file/tZ8uNsqBNHrtIqk8IpqgCo/2023-08-15---TicTacToe-design?type=design&node-id=162%3A63&mode=design&t=NmwFF9z1V82ESXlj-1)
- Images attached

![Image](https://user-images.githubusercontent.com/36261291/266830080-c1c83636-bb1e-4d13-9070-8b78606a2553.png)

## Dev

- [ ] Create new file for this page
- [ ] Update Destinations class in MainActivity for navController
- [ ] Function to handle 3 diff layouts (see sample from HomeScreen.kt)
- [ ] Compact Height UI
- [ ] Compact Width UI
- [ ] Bigger width UI

## Subtasks

- [ ] Components - xxx
- [ ] Components - xxx
- [ ] Components - xxx

## Testing

- [ ] Mobile landscape (Compact Height)
- [ ] Mobile portrait (Compact width)
- [ ] Tablet (all else)

---

#### Sample code

- Useful to reference MultiplayerSelectScreen.kt
