### ISSUE TITLE
User Select Screen - entry from settings (multiplayer)

### ISSUE THREAD

**Issue by JasmineEllaine** [Keven-R/TicTac#21]
# Docs

- [Design specs + layout (Figma)](https://www.figma.com/file/tZ8uNsqBNHrtIqk8IpqgCo/2023-08-15---TicTacToe-design?type=design&node-id=162%3A63&mode=design&t=NmwFF9z1V82ESXlj-1)
- Images attached

![Image](https://user-images.githubusercontent.com/36261291/266830273-563d149f-caad-4133-ab31-95dd7bba447a.png)

## Dev

- [x] Function to handle 2 diff layouts
- [x] Compact Height UI
- [x] All other UI

## Subtasks

- [x] Components - CardButton
- [x] Components - UserCell

## Testing

- [x] Mobile landscape
- [x] Mobile portrait
- [x] Tablet (all else)

---

#### Sample code

- Useful to reference MultiplayerSelectScreen.kt
