### ISSUE TITLE
User Detail Screen

### ISSUE THREAD

**Issue by JasmineEllaine** [Keven-R/TicTac#22]
# Docs

- [Design specs + layout (Figma)](https://www.figma.com/file/tZ8uNsqBNHrtIqk8IpqgCo/2023-08-15---TicTacToe-design?type=design&node-id=162%3A232&mode=design&t=NmwFF9z1V82ESXlj-1)
- Images attached

![Image](https://user-images.githubusercontent.com/36261291/266831265-f91f4b07-e95f-4573-9d15-7556c99c81b4.png)

## Dev

- [x] Function to handle 2 or 3 diff layouts (up to you how to approach it)
- [x] Compact Height UI
- [x] Compact Width UI
- [x] Bigger width UI

## Subtasks

- [x] Components - ImageGridSingleSelect
- [x] Components - ImageGridItem

## Testing

- [x] Mobile landscape (Compact Height)
- [x] Mobile portrait (Compact width)
- [x] Tablet (all else)

---

#### Sample code

- Useful to reference MultiplayerSelectScreen.kt + UserSelectScreen
