### ISSUE TITLE
Home screen

### ISSUE THREAD

**Issue by JasmineEllaine** [Keven-R/TicTac#9]
## Main:

- [x] Size and orientation handler
- [x] Compact UI
- [x] Medium UI
- [x] Expanded UI

### Subtasks:

- [x] Component - PrimaryButton 
- [x] Component - Logo text
- [x] Theme - Setup
- [x] Style - displaySmall
- [x] Style - headlineLarge
- [x] Color - add colours

### Testing:

- [x] Mobile - portrait
- [x] Mobile - landscape
- [x] tablet - portrait
- [x] tablet - landscape
